ATOM_NAME = C
DIM = 3 3 3
#PRIMITIVE_AXIS =  1/2 1/2 0  -1/2 1/2 0 0 0 1
# !!!!!!!!!!! remember the primitive_axis is a column matrix!!!!!!!!!!!!
# !!!!!!!!!!! check band.yaml the reciprocal lattice vectors the Phonopy used!
# GammaK1M1GammaK2M2Gamma
FC_SYMMETRY = .TRUE.
#NAC = .TRUE.
FORCE_CONSTANTS = WRITE
FULL_FORCE_CONSTANTS = .TRUE.
BAND = 0 0 0  1/2 0 1/2,  1/2 1/2 1    3/8 3/8 3/4      0 0 0   1/2 1/2 1/2
BAND_POINTS = 101
BAND_LABELS = Gamma X X  K Gamma  L
# !!!!!!!!!!! remember this is based on the reduced primitive reciprocal lattice vectors!!!!!!!!!!!!!!!!!!!

#BAND = 0 0 0   0 0.343430955983917 -0.343430955983917 0 0.5 0    0 0 0   0.5 0.5 0.5 
#BAND_LABELS = \Gamma X L \Gamma Z


#BAND = 0.268989885161165 0 0     0 0 0     0.231010114838835 0.5 0      0 0.5 0         0 0 0       0 0 0.5      0 0.5 0.5     0 0 0    
#BAND_LABELS = X \Gamma X1 Y \Gamma Z T \Gamma
#BAND = 0 0 0     1 0 0 , 0 0 0    0 1 0, 0 0 0    0 0 1
#BAND_LABELS = \Gamma X/\Gamma Y/\Gamma Z
#BAND = 0 0 0     0.268989885161165 0 0   ,   0.231010114838835 0.5 0     0 0.5 0         0 0 0     0 0 0.5 
#BAND_LABELS = \Gamma X/X$_1$  Y \Gamma Z
BAND_CONNECTION = .TRUE.
