ATOM_NAME = Ti
DIM = 3 3 3

# Do NOT use PRIMITIVE_AXIS for a standard HCP cell. 
# The VASP POSCAR is already primitive.

FC_SYMMETRY = .TRUE.

# NAC is commented out, which is CORRECT for a metal like Ti
#NAC = .TRUE.

FORCE_CONSTANTS = WRITE
FULL_FORCE_CONSTANTS = .TRUE.

# Continuous Standard HCP Phonon Path
# Gamma -> M -> K -> Gamma -> A -> L -> H -> A
BAND = 0.0 0.0 0.0  0.5 0.0 0.0  0.3333333 0.3333333 0.0  0.0 0.0 0.0  0.0 0.0 0.5  0.5 0.0 0.5  0.3333333 0.3333333 0.5  0.0 0.0 0.5
BAND_POINTS = 101
BAND_LABELS = Gamma M K Gamma A L H A
BAND_CONNECTION = .TRUE.