ATOM_NAME = Zr
DIM = 4 4 4

# Automatically converts your 2-atom conventional cell to the 1-atom primitive BCC cell
PRIMITIVE_AXIS = AUTO

FC_SYMMETRY = TRUE
FORCE_CONSTANTS = WRITE
FULL_FORCE_CONSTANTS = TRUE

# Standard BCC high-symmetry path
BAND = 0.0 0.0 0.0  0.5 -0.5 0.5  0.25 0.25 0.25  0.0 0.0 0.0  0.0 0.0 0.5  0.25 0.25 0.25
BAND_LABELS = Gamma H P Gamma N P
BAND_POINTS = 101
BAND_CONNECTION = TRUE
